### Registro de Usuario
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Ignacio Ledesma",
  "email": "ignacio@admin.com",
  "password": "mi_password_seguro_123"
}

###

### 2. Login de Usuario (Conseguir el Token)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "ignacio@admin.com",
  "password": "mi_password_seguro_123"
}

### Crear Cuenta Bancaria
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZ25hY2lvQGFkbWluLmNvbSIsImlhdCI6MTc2ODk0NTc1OSwiZXhwIjoxNzY5MDMyMTU5fQ.kha6hnj33AbqAo597VUwOE0ELXz4PozqRJ_PLfggA7k

{
  "currency": "USD"
}

### Ver mis Cuentas (Consultar Saldo)
GET http://localhost:8080/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZ25hY2lvQGFkbWluLmNvbSIsImlhdCI6MTc2ODk0NjI0OSwiZXhwIjoxNzY5MDMyNjQ5fQ.8L_ZpEkmLoJ10muYY3yKeq9iVWDmlxLG-MRWc6VB7hY

### Depositar Dinero
POST http://localhost:8080/transactions/deposit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZ25hY2lvQGFkbWluLmNvbSIsImlhdCI6MTc2ODk0ODI2OSwiZXhwIjoxNzY5MDM0NjY5fQ.0x50U6hDeD3EgKlKp1gJbM_zhry57kMoQzTMjJyGXf4

{
  "cbu": "1768945902491129386148",
  "amount": 500.00
}

### 1. Transferir Dinero
POST http://localhost:8080/transactions/transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZ25hY2lvQGFkbWluLmNvbSIsImlhdCI6MTc2ODk1MDY3MywiZXhwIjoxNzY5MDM3MDczfQ.LGxqKrPOu5WKW9gV165AdxSiaDCpBrI_6QC78JxAWkE

{
  "sourceCbu": "1768945902491129386148",
  "destinationCbu": "1768949494197346134556",
  "amount": 100.00
}

### Ver Historial de Transacciones
GET http://localhost:8080/transactions/1768945902491129386148
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZ25hY2lvQGFkbWluLmNvbSIsImlhdCI6MTc2ODk1MDY3MywiZXhwIjoxNzY5MDM3MDczfQ.LGxqKrPOu5WKW9gV165AdxSiaDCpBrI_6QC78JxAWkE
